import {
  ADMINS_PACKAGE_NAME,
  AUTH_PACKAGE_NAME,
  FILES_PACKAGE_NAME,
  INVITES_PACKAGE_NAME,
  MAIL_PACKAGE_NAME,
  SCHOOL_PACKAGE_NAME,
  TEACHERS_PACKAGE_NAME,
} from '../'

export enum Packages {
  AUTH = AUTH_PACKAGE_NAME,
  MAIL = MAIL_PACKAGE_NAME,
  ADMINS = ADMINS_PACKAGE_NAME,
  FILES = FILES_PACKAGE_NAME,
  INVITES = INVITES_PACKAGE_NAME,
  SCHOOL = SCHOOL_PACKAGE_NAME,
  TEACHERS = TEACHERS_PACKAGE_NAME,
}
