import {
  ADMINS_PACKAGE_NAME,
  AUTH_PACKAGE_NAME,
  CLASS_PACKAGE_NAME,
  FILES_PACKAGE_NAME,
  INVITES_PACKAGE_NAME,
  MAIL_PACKAGE_NAME,
  NOTIFICATIONS_PACKAGE_NAME,
  SCHOOL_EVENTS_PACKAGE_NAME,
  SCHOOL_PACKAGE_NAME,
  SCHOOL_STATISTIC_PACKAGE_NAME,
  TEACHERS_PACKAGE_NAME,
  TOP_QUESTIONS_PACKAGE_NAME,
} from '../'

export enum Packages {
  AUTH = AUTH_PACKAGE_NAME,
  MAIL = MAIL_PACKAGE_NAME,
  ADMINS = ADMINS_PACKAGE_NAME,
  FILES = FILES_PACKAGE_NAME,
  INVITES = INVITES_PACKAGE_NAME,
  SCHOOL = SCHOOL_PACKAGE_NAME,
  TEACHERS = TEACHERS_PACKAGE_NAME,
  SCHOOL_STATISTIC = SCHOOL_STATISTIC_PACKAGE_NAME,
  SCHOOL_EVENTS = SCHOOL_EVENTS_PACKAGE_NAME,
  NOTIFICATIONS = NOTIFICATIONS_PACKAGE_NAME,
  TOP_QUESTIONS = TOP_QUESTIONS_PACKAGE_NAME,
  CLASS = CLASS_PACKAGE_NAME,
}
