// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v5.26.1
// source: proto/entities.proto

/* eslint-disable */

export const protobufPackage = 'entities'

export interface SchoolEntityDto {
  name: string
  avatarUrl: string
  location: string
  licenseNumber: string
  licenseImg: string
  owner: AccountEntityDto | undefined
  pointsSystem: string
  ip: string
  region: string
  IsActivated: boolean
  blocked: boolean
  id: number
  createAt: Date
  updateAt: Date
  students: StudentAccDto[]
  teachers: TeacherEntityDto[]
  lessons: LessonEntityDto[]
  classes: ClassEntityDto[]
  moderators: ModeratorAccDto[]
  description: string
}

export interface AccountEntityDto {
  id: number
  createAt: Date
  updateAt: Date
  userId: UserEntityDto | undefined
  school: SchoolEntityDto | undefined
  role: string
  isAccepted?: boolean | undefined
}

export interface ModeratorAccDto {
  id: number
  createAt: Date
  updateAt: Date
  userId: UserEntityDto | undefined
  school: SchoolEntityDto | undefined
  role: string
  isActivated: boolean
}

export interface UserEntityDto {
  id: number
  name: string
  middlename: string
  surname: string
  createAt: Date
  updateAt: Date
  email: string
  avatar: string
  isActivated: boolean
  blocked: boolean
  blockedDescription: string
}

export interface StudentAccDto {
  id: number
  createAt: Date
  updateAt: Date
  isAdmit: boolean
  school: SchoolEntityDto | undefined
  dateOfAccession: Date
  userId: UserEntityDto | undefined
  class: ClassEntityDto[]
  points: PointEntityDto[]
}

export interface TeacherEntityDto {
  id: number
  createAt: Date
  updateAt: Date
  isAdmit: boolean
  userId: UserEntityDto | undefined
  school: SchoolEntityDto | undefined
  OpeningTimes: string
  role: string
  class: ClassEntityDto[]
  lessons: LessonEntityDto[]
}

export interface ClassEntityDto {
  id: number
  createAt: Date
  updateAt: Date
  name: number
  parallel: string
  school: SchoolEntityDto | undefined
  chiefs: TeacherEntityDto[]
  students: StudentAccDto[]
  lessons: LessonEntityDto[]
  points: PointEntityDto[]
}

export interface LessonEntityDto {
  id: number
  createAt: Date
  updateAt: Date
  lessonName: string
  icon: string
  school: SchoolEntityDto | undefined
  teacher: TeacherEntityDto[]
  classes: ClassEntityDto[]
}

export interface PointEntityDto {
  id: number
  createAt: Date
  updateAt: Date
  point: string
  description: string
  student: StudentAccDto | undefined
  lesson: LessonEntityDto | undefined
  school: SchoolEntityDto | undefined
  classe: ClassEntityDto | undefined
  type: string
}

export interface SchoolEventEntityDto {
  id: number
  createAt: Date
  updateAt: Date
  title: string
  description: string
  tags: string[]
  creator: UserEntityDto | undefined
  school: SchoolEntityDto | undefined
  activeTeachers: TeacherEntityDto[]
  activeStudents: StudentAccDto[]
  activeClasses: ClassEntityDto[]
  plannedDate: string
  views: number
  image: string
  isPrivate: boolean
}

export interface PointNotificationEntityDto {
  id: number
  createAt: string
  updateAt: string
  to: UserEntityDto | undefined
  title: string
  description: string
  point: PointEntityDto | undefined
  creator: UserEntityDto | undefined
}

export interface QuestionEntityDto {
  id: number
  createAt: string
  updateAt: string
  title: string
  comment: string
  creator: UserEntityDto | undefined
  role: string
  school: SchoolEntityDto | undefined
  likes: LikeEntityDto[]
  questionComments: TopQuestionCommentEntityDto[]
  likesCount: number
}

export interface LikeEntityDto {
  id: number
  createAt: string
  updateAt: string
  user: UserEntityDto | undefined
  question: QuestionEntityDto | undefined
}

export interface TopQuestionCommentEntityDto {
  id: number
  createAt: string
  updateAt: string
  comment: string
  creator: UserEntityDto | undefined
  responseComment: TopQuestionCommentEntityDto | undefined
  question: QuestionEntityDto | undefined
}

export const ENTITIES_PACKAGE_NAME = 'entities'
