// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v5.26.1
// source: proto/notifications.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices'

export const protobufPackageNotifications = 'notifications'

export const NOTIFICATIONS_PACKAGE_NAME = 'notifications'

export interface NotificationsServiceClient {}

export interface NotificationsServiceController {}

export function NotificationsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = []
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method)
      GrpcMethod('NotificationsService', method)(constructor.prototype[method], method, descriptor)
    }
    const grpcStreamMethods: string[] = []
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method)
      GrpcStreamMethod('NotificationsService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      )
    }
  }
}

export const NOTIFICATIONS_SERVICE_NAME = 'NotificationsService'
