// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v5.26.1
// source: proto/teachers.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices'
import { Observable } from 'rxjs'
import { TeacherEntityDto } from './entities'

export const protobufPackageTeachers = 'teachers'

export interface QueryTeachersDto {
  search?: string | undefined
  page: string
  limit?: string | undefined
  sortData?: string | undefined
  schoolId: string
}

export interface GetTeacherByIdDto {
  teacherId: number
}

export interface ReturnOneTeacherDto {
  message: string
  teacher: TeacherEntityDto | undefined
}

export interface ReturnAllTeachersDto {
  count: number
  data: TeacherEntityDto[]
}

export const TEACHERS_PACKAGE_NAME = 'teachers'

export interface TeachersServiceClient {
  getAllTeachers(request: QueryTeachersDto): Observable<ReturnAllTeachersDto>

  getTeacherById(request: GetTeacherByIdDto): Observable<ReturnOneTeacherDto>
}

export interface TeachersServiceController {
  getAllTeachers(
    request: QueryTeachersDto,
  ): Promise<ReturnAllTeachersDto> | Observable<ReturnAllTeachersDto> | ReturnAllTeachersDto

  getTeacherById(
    request: GetTeacherByIdDto,
  ): Promise<ReturnOneTeacherDto> | Observable<ReturnOneTeacherDto> | ReturnOneTeacherDto
}

export function TeachersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['getAllTeachers', 'getTeacherById']
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method)
      GrpcMethod('TeachersService', method)(constructor.prototype[method], method, descriptor)
    }
    const grpcStreamMethods: string[] = []
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method)
      GrpcStreamMethod('TeachersService', method)(constructor.prototype[method], method, descriptor)
    }
  }
}

export const TEACHERS_SERVICE_SERVICE_NAME = 'TeachersService'
